/**
 * Generates src/lib/geo/tennessee.ts — a small GeoJSON Feature for Tennessee —
 * from us-atlas (public domain, US Census Bureau). Coordinates are rounded to
 * shrink the client payload. Run with `pnpm generate:geo`.
 */
import fs from "node:fs";
import path from "node:path";
import { feature } from "topojson-client";
import type { FeatureCollection } from "geojson";

type Nested = number | Nested[];

function round(value: Nested): Nested {
  if (typeof value === "number") return value;
  if (typeof value[0] === "number") {
    return (value as number[]).map((n) => Math.round(n * 1000) / 1000);
  }
  return value.map(round);
}

const SRC = path.join(
  process.cwd(),
  "node_modules",
  "us-atlas",
  "states-10m.json",
);
const OUT = path.join(process.cwd(), "src", "lib", "geo", "tennessee.ts");

const topo = JSON.parse(fs.readFileSync(SRC, "utf8")) as Parameters<
  typeof feature
>[0];
const states = feature(
  topo,
  topo.objects.states,
) as unknown as FeatureCollection;

const tn = states.features.find((f) => String(f.id) === "47");
if (!tn) {
  throw new Error("Tennessee (FIPS 47) not found in us-atlas states-10m.");
}

const geom = tn.geometry as { type: string; coordinates: Nested };
geom.coordinates = round(geom.coordinates);

const banner =
  "// AUTO-GENERATED by scripts/build-tn-geo.ts from us-atlas (public domain, US Census Bureau).\n" +
  "// Do not edit by hand — run `pnpm generate:geo`.\n\n";
const body =
  'import type { Feature, Geometry } from "geojson";\n\n' +
  `export const TENNESSEE = ${JSON.stringify(tn)} as Feature<Geometry>;\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, banner + body);

const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
console.log(`✓ wrote ${path.relative(process.cwd(), OUT)} (${kb} KB)`);
